"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var account_controller_1 = require("../controllers/account.controller");
var auth_1 = require("../middleware/auth");
var router = (0, express_1.Router)();
router.post('/', auth_1.authenticateToken, account_controller_1.createAccount);
router.get('/', auth_1.authenticateToken, account_controller_1.getAccounts);
router.get('/grouped', auth_1.authenticateToken, account_controller_1.getGroupedAccounts);
exports.default = router;
