"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var budget_controller_1 = require("../controllers/budget.controller");
var auth_1 = require("../middleware/auth");
var router = (0, express_1.Router)();
router.get('/budget', auth_1.authenticateToken, budget_controller_1.getBudget);
router.get('/budget/template', auth_1.authenticateToken, budget_controller_1.getBudgetTemplate);
router.post('/budget/auto', auth_1.authenticateToken, budget_controller_1.autoGenerateBudget);
router.post('/budget', auth_1.authenticateToken, budget_controller_1.saveBudget);
exports.default = router;
