"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_1 = require("../middleware/auth");
var controller = require("../controllers/report.controller");
var router = (0, express_1.Router)();
router.get('/monthly-expenses', auth_1.authenticateToken, controller.getMonthlyExpensesByCategory);
router.get('/monthly-summary', auth_1.authenticateToken, controller.getMonthlySummary);
router.get('/expenses-by-category', auth_1.authenticateToken, controller.getExpensesByCategory);
router.get('/income-by-category', auth_1.authenticateToken, controller.getIncomeByCategory);
router.get('/account-balance', auth_1.authenticateToken, controller.getAccountBalances);
router.get('/expense-by-thirty', auth_1.authenticateToken, controller.getExpenseThirty);
router.get('/expense-trend', auth_1.authenticateToken, controller.getMonthlyExpenseTrend);
exports.default = router;
