"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var transaction_controller_1 = require("../controllers/transaction.controller");
var auth_1 = require("../middleware/auth");
var router = (0, express_1.Router)();
router.post('/', auth_1.authenticateToken, transaction_controller_1.createTransaction);
router.get('/', auth_1.authenticateToken, transaction_controller_1.getTransactions);
router.get('/:id', auth_1.authenticateToken, transaction_controller_1.getTransactionById);
router.delete('/:id', auth_1.authenticateToken, transaction_controller_1.deleteTransaction);
router.put('/:id', auth_1.authenticateToken, transaction_controller_1.updateTransaction);
exports.default = router;
